# Generated by Django 3.2.6 on 2021-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('review_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('review_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('review_star', models.IntegerField()),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hibernate_sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(blank=True, null=True)),
                ('history_oneline', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryBooksImgurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_books_imgurl_0', models.CharField(blank=True, db_column='history_books_imgurl', max_length=255, null=True)),
            ],
            options={
                'db_table': 'history_books_imgurl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryBooksIsbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_books_isbns', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'history_books_isbn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mybook_author', models.CharField(blank=True, max_length=255, null=True)),
                ('mybook_date', models.DateTimeField(blank=True, null=True)),
                ('mybook_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('mybook_imgurl', models.CharField(blank=True, max_length=255, null=True)),
                ('mybook_isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('mybook_published', models.CharField(blank=True, max_length=255, null=True)),
                ('mybook_publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('mybook_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('review_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('review_star', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmpbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_coll_aladin', models.CharField(blank=True, max_length=255, null=True)),
                ('is_coll_naver', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_star', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tmpbooks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_pw', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
